---
- name: "Deploy the monitoring stack locally"
  hosts: local
  become: true
  vars:
    project_root: "{{ playbook_dir }}/.."
  roles:
    - common
    - docker_setup
    - filebeat_agent
    - monitoring_stack
