---
- name: Copy Prometheus config
  ansible.builtin.copy:
    src: prometheus.yml
    dest: "{{ project_root }}/prometheus/prometheus.yml"
    mode: "0644"

- name: Copy Grafana provisioning assets
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ project_root }}/grafana/provisioning/{{ item }}"
    mode: "0644"
  loop:
    - datasources/prometheus.yml
    - dashboards/home-dashboard.json

- name: Render docker-compose.yml from template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ project_root }}/docker-compose.yml"
    mode: "0644"
  notify: Restart monitoring stack
