- name: Ensure secrets dir exists
  file:
    path: "{{ project_root }}/secrets"
    state: directory
    mode: "0700"

- name: Generate Grafana admin password (once)
  set_fact:
    grafana_admin_password: >-
      {{
        lookup(
          'password',
          project_root ~ '/secrets/.grafana_admin_pass',
          length=24,
          chars='ascii_letters'
        )
      }}
  no_log: true

- name: Write secret file for Docker Compose
  copy:
    dest: "{{ project_root }}/secrets/grafana_admin_password"
    content: "{{ grafana_admin_password }}"
    mode: "0400"
  no_log: true
