---
- name: Set up monitoring directories
  ansible.builtin.import_tasks: setup_dirs.yml
  tags: [install, stack]

- name: Generate monitoring stack secrets
  ansible.builtin.import_tasks: generate_secrets.yml
  tags: [install]

- name: Deploy monitoring stack via Docker Compose
  ansible.builtin.import_tasks: deploy_compose.yml
  tags: [install, stack]

- name: Start monitoring stack services
  ansible.builtin.import_tasks: start_stack.yml
  tags: [install, stack]

- name: Wait for monitoring services to be ready
  ansible.builtin.import_tasks: wait_services.yml
  tags: [install, grafana]

- name: Provision Grafana dashboards
  ansible.builtin.import_tasks: grafana_dashboards.yml
  tags: [install, grafana]

- name: Clean up temporary setup files
  ansible.builtin.import_tasks: cleanup.yml
  tags: [cleanup]
