---
- name: Ensure Prometheus & Grafana dirs exist
  ansible.builtin.file:
    path: "{{ project_root }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - prometheus
    - grafana/config
    - grafana/provisioning/datasources
    - grafana/provisioning/dashboards
