- name: Wait for Grafana port to be open
  ansible.builtin.wait_for:
    host: localhost
    port: 80
    timeout: 120

- name: Wait for Grafana HTTP API to respond 200
  ansible.builtin.uri:
    url: http://localhost:80/api/health
    status_code: 200
    validate_certs: no
  register: grafana_health
  until: grafana_health.status == 200
  retries: 30
  delay: 2

- name: Wait for Prometheus port to be open
  ansible.builtin.wait_for:
    host: localhost
    port: 9090
    timeout: 60
