---
filebeat.inputs:
  - type: filestream
    id: docker-logs
    parsers:
      - container:
          format: docker
          stream: all
    paths:
      - /var/lib/docker/containers/*/*-json.log

processors:
  - add_docker_metadata:

output.file:
  path: "/var/log"
  filename: "test"
  rotate_every_kb: 10000
  number_of_files: 5

http.enabled: true
http.host: "0.0.0.0"
http.port: 5066
