name: Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install ansible + ansible-lint
        run: python -m pip install --upgrade pip && pip install "ansible>=2.17" ansible-lint -q

      - name: Install Galaxy collections
        run: ansible-galaxy collection install -r ansible/requirements.yml

      - name: Run ansible-lint
        run: ansible-lint ansible/

      - name: Syntax check
        run: ansible-playbook -i localhost, -c local ansible/site.yml --syntax-check
