name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_COLLECTIONS_PATHS: ${{ github.workspace }}/.ansible/collections

    steps:
      - uses: actions/checkout@v3

      - name: Cache Galaxy collections
        uses: actions/cache@v3
        with:
          path: .ansible/collections
          key: ${{ runner.os }}-galaxy-${{ hashFiles('ansible/requirements.yml') }}
          restore-keys: ${{ runner.os }}-galaxy-

      - name: Install Galaxy collections
        run: |
          mkdir -p .ansible/collections
          ansible-galaxy collection install -r ansible/requirements.yml -p .ansible/collections

      - uses: ansible/ansible-lint-action@v6
        with:
          path: ansible/

      - name: Syntax check
        run: ansible-playbook -i localhost, -c local ansible/site.yml --syntax-check
